# Generated by Django 4.2.7 on 2023-11-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='path',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
